# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: hybrid-committed-spend-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: hybrid-committed-spend
    spec:
      feoConfigEnabled: false
      searchEntries:
        - id: 'hybrid-committed-spend'
          title: 'Hybrid Committed Spend'
          href: '/subscriptions/hybrid-committed-spend'
          description: 'Gain perspective on your hybrid committed spend profile with contract information, drawdown, and balance, as well as spend trends and breakdowns.'
          alt_title:
            - 'Hybrid Committed Spend'
      bundleSegments:
        - segmentId: 'hybrid-committed-spend'
          bundleId: 'subscriptions'
          position: 100
          navItems:
            - id: 'hybrid-committed-spend.overview'
              title: 'Overview'
              href: '/subscriptions/hybrid-committed-spend'
              permissions:
                - method: 'hasPermissions'
                  args:
                    - - "hybrid-committed-spend:reports:read"
            - id: 'hybrid-committed-spend.details'
              title: 'Details'
              href: '/subscriptions/hybrid-committed-spend/details'
              permissions:
                - method: 'hasPermissions'
                  args:
                    - - "hybrid-committed-spend:reports:read"
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: 'Hybrid Committed Spend'
      deploymentRepo: https://github.com/RedHatInsights/hybrid-committed-spend-ui
      frontend:
        paths:
          - /apps/hybrid-committed-spend
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/hybrid-committed-spend/fed-mods.json"
        modules:
          - id: 'hybrid-committed-spend'
            module: "./RootApp"
            routes:
              - pathname: /subscriptions/hybrid-committed-spend
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/rh-hcs-tenant/hcs-frontend
