{
 "title": "Frontend SLO Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "frontend",
    "query": {
     "query": "label_values(caddy_http_requests_total, job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(caddy_http_requests_total, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_requests_total{job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[30d]))"
    }
   ]
  },
  {
   "title": "Status code proportions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(promhttp_metric_handler_requests_total{job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m])) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "SLO for Error [30d]",
   "type": "graph",
   "description": "Visualization of SLO movement",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1.00 - (sum(rate(caddy_http_request_errors_total{job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[30d])) / sum(rate(caddy_http_requests_total{job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[30d]))) OR on() vector(1)",
     "legendFormat": "SLO at time [30d]"
    }
   ]
  },
  {
   "title": "Latency Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"0.5\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m]))) > 0",
     "legendFormat": "Less than 500ms"
    },
    {
     "expr": "(sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"1.0\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m])) - sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"0.5\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m]))) > 0",
     "legendFormat": "500 - 1000ms"
    },
    {
     "expr": "(sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"2.5\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m])) - sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"1.0\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m]))) > 0",
     "legendFormat": "1000 - 2500ms"
    },
    {
     "expr": "(sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"5.0\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m])) - sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"2.5\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m]))) > 0",
     "legendFormat": "5000 - 2500ms"
    },
    {
     "expr": "(sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"10.0\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m])) - sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"5.0\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m]))) > 0",
     "legendFormat": "5000 - 1000ms"
    },
    {
     "expr": "(sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"+Inf\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m])) - sum by(job) (rate(caddy_http_response_duration_seconds_bucket{le=\"10.0\", job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[5m]))) > 0",
     "legendFormat": "> 10000ms"
    }
   ]
  },
  {
   "title": "SLO for latency [30d]",
   "type": "graph",
   "description": "Visualization of SLO movement",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_bucket{job=\"[[frontend]]\", le=\"5.0\", namespace=\"[[namespace]]\"}[30d])) / sum(rate(caddy_http_request_duration_seconds_count{job=\"[[frontend]]\", namespace=\"[[namespace]]\"}[30d]))",
     "legendFormat": "SLO at time [30d]"
    }
   ]
  }
 ]
}